apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: o7hw8gx2j-java-quarkus 
  janus-idp.io/tekton: o7hw8gx2j-java-quarkus
  backstage.io/kubernetes-id: o7hw8gx2j-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: o7hw8gx2j-java-quarkus
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  